version: '3.9'
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns@sha256:9da09dd199afcda941dcb1e26d31463c84a144d6172342da84b19a5a9c3b85be
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/cloudflare-ddns/config.json:/config.json
    restart: unless-stopped
