version: '3.9'
services:
  cloudflare-ddns:
    #image: timothyjmiller/cloudflare-ddns@sha256:80b61507b8ca2e68755a921df776b9a019b4933df34d7af9109ad99cf549551e
    image: raidowl/cloudflare-ddns@sha256:ea2e21147cf121c7a875d6b3ca4abf575a0f2a98415cae53ce0f28dbae18f7f1
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/cloudflare-ddns/config.json:/config.json
    restart: unless-stopped
