version: '3.9'
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns@sha256:d6a45a488d84215c04cae5f25dae69bc206082a4d02bae8cbd91e7f5fa8ce2d7
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/cloudflare-ddns/config.json:/config.json
    restart: unless-stopped
