version: "3"

services:
  couchdb:
    image: couchdb:3.5.1
    container_name: couchdb
    environment:
      - COUCHDB_USER=${DB_USERNAME}  #Please change as you like.
      - COUCHDB_PASSWORD=${DB_PASSWORD} #Please change as you like.
    volumes:
      - /docker/couchdb/data:/opt/couchdb/data
      - /docker/couchdb/etc:/opt/couchdb/etc/local.d
    networks:
      nginx-bridge:
    restart: unless-stopped
    
networks:
  nginx-bridge:
    name: nginx-bridge
    external: true
