version: '3.8'

services:
  freshrss:
    image: freshrss/freshrss:1.28.1
    container_name: freshrss
    restart: unless-stopped
    # ports:
    #   - "8080:80"
    environment:
      TZ: Europe/Warsaw
      CRON_MIN: "1,31"
    volumes:
      - /docker/freshrss/data:/var/www/FreshRSS/data
      - /docker/freshrss/extensions:/var/www/FreshRSS/extensions
    networks:
      nginx-bridge:

networks:
  nginx-bridge:
    name: nginx-bridge
    external: true
