version: "3.9"
services:
  gatus:
    container_name: gatus
    image: twinproduction/gatus:v5.22.0
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME} 
      - POSTGRES_PASSWORD=${DB_PASSWORD} 
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_HOSTNAME=${DB_HOSTNAME}
    volumes:
      - /docker/gatus:/config
    networks:
      nginx-bridge:
      
networks:
  nginx-bridge:
    name: nginx-bridge
    external: true
