version: "3.9"
services:
  gatus:
    image: twinproduction/gatus:v5.16.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=${DB_USERNAME} 
      - POSTGRES_PASSWORD=${DB_PASSWORD} 
      - POSTGRES_DB=${DB_DATABASE_NAME}
    volumes:
      - /docker/gatus:/config
      
networks:
  nginx-bridge:
    name: nginx-bridge
    external: true
