services:
  immich-kiosk:
    image: ghcr.io/damongolding/immich-kiosk:0.36.3
    container_name: immich-kiosk
    tty: true
    environment:
      LANG: "pl_PL"
      TZ: "Europe/Warsaw"
    volumes:
      - /docker/immich-kiosk/config:/config
      # - ./custom.css:/custom.css
      # - ./offline-assets:/offline-assets
    networks:
      nginx-bridge:
      
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://immich-kiosk:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
networks:
  nginx-bridge:
    name: nginx-bridge
    external: true
