version: "3"
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:v0.10.0
    container_name: nebula-sync
    environment:
      PRIMARY: ${PRIMARY}
      REPLICAS: ${REPLICAS}
      FULL_SYNC: "true"
      RUN_GRAVITY: "false"
      CRON: "*/15 * * * *"
      TZ: "Europe/Warsaw"
      CLIENT_SKIP_TLS_VERIFICATION: "true"
