version: "3"

services:

  nginx-balancer:
    container_name: nginx-balancer
    image: nginx:1.25.4
    volumes:
      - /docker/nginx-balancer:/etc/nginx
    ports:
      - "80:80"
    networks:
      macvlan:
        ipv4_address: 192.168.1.201
      bridge:
    restart: unless-stopped

networks:
  macvlan:
    name: macvlan
    external: true
  bridge:
    name: nginx-bridge
    external: true
      
