version: "3"

services:

  nginx-balancer:
    container_name: nginx-balancer
    image: nginx:1.29.3
    volumes:
      - /docker/nginx-balancer/nginx.conf:/etc/nginx/nginx.conf
      - /docker/nginx-balancer/sites-enabled:/etc/nginx/sites-enabled
      # - /docker/nginx-balancer/logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    networks:
      nginx-bridge:

    restart: unless-stopped

networks:
  nginx-bridge:
    name: nginx-bridge
    external: true
      
