version: "3"

services:

  nginx-balancer:
    container_name: nginx-balancer
    image: nginx:1.27.3
    volumes:
      - /docker/nginx-balancer/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      macvlan:
        ipv4_address: 192.168.1.201
      nginx-bridge:

    restart: unless-stopped

networks:
  macvlan:
    name: macvlan
    external: true
  nginx-bridge:
    name: nginx-bridge
    external: true
      
