version: "3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.38.1-alpine

    ports:
      - "8000:8000/tcp"
      - "9443:9443/tcp"
     
    networks:
      macvlan:
        ipv4_address: 10.203.32.70
    environment:
      TZ: 'Europe/Warsaw'
    
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/docker/portainer/data:/data'

    restart: unless-stopped


networks:
  macvlan:
    name: macvlan
    external: true


