version: '3'
services:

  postgres:
      container_name: postgres
      image: postgres:18.0
      restart: unless-stopped
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
        - /docker/postgres/data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      networks:
        nginx-bridge:

networks:
  nginx-bridge:
    name: nginx-bridge
    external: true
