version: '3'
services:

  postgres:
      container_name: postgres
      image: postgres:16.2
      restart: always
      environment:
        POSTGRES_DB: ${DB_DATABASE_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
        - /docker/postgres/data:/var/lib/postgresql/data
      networks:
        bridge:

networks:
  bridge:
    name: nginx-bridge
    external: true
