version: "3"

services:
  postgres-immich:
   container_name: postgres-immich
   image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
   environment:
     POSTGRES_PASSWORD: ${DB_PASSWORD}
     POSTGRES_USER: ${DB_USERNAME}
     POSTGRES_DB: ${DB_DATABASE_NAME}
   volumes:
     - /docker/postgres-immich/data:/var/lib/postgresql/data
   networks:
     bridge:
   restart: always


networks:
  bridge:
    name: nginx-bridge
    external: true
