version: '3'
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-05-28T17-19-04Z
    volumes:
      - /mnt/data/minio:/data
    ports:
      - 9000:9000
      - 9002:9001
    environment:
      MINIO_ROOT_USER:  ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: server /data
    restart: unless-stopped
